name: Check PR Source Branch
on: [pull_request]
jobs:
  validate-source:
    runs-on: ubuntu-latest
    if: github.base_ref == 'main'
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.head_ref }}" != "staging" ]]; then
            echo "PR must originate from staging branch in order to merge the code to main(Production)"
            exit 1
          fi

